ControleDeVistoria.Web/Controllers/ImovelController.cs
using ControleDeVistoria.Application.Interfaces;
using ControleDeVistoria.Application.ViewModels;
using ControleDeVistoria.Infra.Data.IdentityData.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ControleDeVistoria.Web.Controllers
{
    
    public class ImovelController : Controller
    {
        private readonly IImovelService _imovelService;
        private readonly UserManager<ControleDeVistoriaIdentityUser> _userManager; 

        public ImovelController(IImovelService imovelService, UserManager<ControleDeVistoriaIdentityUser> userManager)
        {
            _imovelService = imovelService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _imovelService.BuscarTodos();
            return View(result);
        }   

        public IActionResult CriarEditar(int? id)
        {
            if (id != null && id != 0)
            {
                ImovelViewModel imovel = _imovelService.BuscarPorId(id.Value).Result;
                ViewData["UserID"] = _userManager.GetUserId(this.User);
                return View(imovel);
            }
            ViewData["UserID"] = _userManager.GetUserId(this.User);
            return View();
        }

        [HttpPost]
        public IActionResult CriarEditar(ImovelViewModel imovel)

        {
            if (ModelState.IsValid)
            {
                if (imovel.Id > 0)
                {
                    if (_imovelService.IdExiste(imovel.Id))
                    {
                        _imovelService.Atualizar(imovel);
                        TempData["mensagem"] = MensagemViewModel.Serializar("Dados atualizados com sucesso!");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemViewModel.Serializar("Não foi possivel atualizar os dados!", Domain.Enums.TipoMensagem.Erro);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    _imovelService.Adicionar(imovel);
                    TempData["mensagem"] = MensagemViewModel.Serializar("Dados cadastrados com sucesso!");
                    return RedirectToAction("Index");
                }
            }
            ViewData["UserID"] = _userManager.GetUserId(this.User);
            return View(imovel); 
        }

        public IActionResult ExcluirConfirmacao(int id)
        {
            if (_imovelService.IdExiste(id))
            {
                ImovelViewModel ImovelDb = _imovelService.BuscarPorId(id).Result;
                return View(ImovelDb);
            }
            TempData["mensagem"] = MensagemViewModel.Serializar("Imovel não encontrado.", Domain.Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int id)
        {
            if (_imovelService.IdExiste(id))
            {
                _imovelService.Excluir(id);
                TempData["mensagem"] = MensagemViewModel.Serializar("Imóvel excluido com sucesso!");
                return RedirectToAction("Index");
            }
            TempData["mensagem"] = MensagemViewModel.Serializar("Houve um erro na exclusão do imóvel!", Domain.Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }






    }
}

ControleDeVistoria.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ControleDeVistoria.Infra.Data.IdentityData.Data

@inject SignInManager<ControleDeVistoriaIdentityUser> SignInManager
@inject UserManager<ControleDeVistoriaIdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VistoriaApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleDeVistoria.Web.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VistoriaApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">



                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Imovel" asp-action="Index">Imóveis</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vistoriador" asp-action="Index">Vistoriador</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vistoria" asp-action="Index">Vistoria</a>
                        </ul>
                    }

                    <partial name="_LoginPartial.cshtml" />
                       
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; 2023 - VistoriaApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ControleDeVistoria.Web/Views/Shared/_Mensagem.cshtml
@using ControleDeVistoria.Application.ViewModels;

@if (TempData.ContainsKey("mensagem")) 
{
    var mensagem = MensagemViewModel.Desserializar(TempData["mensagem"].ToString()); 

    @if (mensagem.Tipo == ControleDeVistoria.Domain.Enums.TipoMensagem.Erro)
    {
        <div class="alert alert-warning mt-3 alert-dismissible fade show" role="alert">
            @mensagem.Texto
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
    else
    {
        <div class="alert alert-success mt-3 alert-dismissible fade show" role="alert">
            @mensagem.Texto
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
}